### PR TITLE
Increase rates precision

### PR DESCRIPTION
**Pull request by printercu**
I've changed amount in request to 1000. Seems like it'll increase precision with 3 digits for free. wdyt?

### CODE REVIEW

**Comment by semmons99** [comment]
Looks like it changes results given the spec failure.

**Comment by printercu** [comment]
Yeah, it's stubbed. I can fix specs & readme if you like the idea.

**Comment by semmons99** [comment]
I'm cool with that. Make sure to update the changelog too

**Comment by printercu** [comment]
I've checked, google doesn't round after conversion, but applies rounded rates. So there is no difference what amount is converted. Sorry.

**Comment by yinquanteo** [comment]
Yes, that's right, this is evident if you play around with [Google Finance Calculator](https://www.google.com/finance/converter)

**Pull request closed without merging**
